name: Node.js tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]

    steps:
      - uses: actions/checkout@v3
      - name: Install pnpm
        uses: pnpm/action-setup@v2.0.1
        with: 
          version: next-7
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Setup
        run: pnpm setup
      - name: Install packages
        run: pnpm ci
      - name: Audit
        run: pnpm audit
      - name: Build
        run: pnpm build
      - name: Test
        run: pnpm test